/* Div IDs in Index.html */
COLLAPSIBLE_TREE_ID = "#collapsible_tree"
BAR_GRAPH_ID = "#bar_graph"
RADAR_CHART_ID = "#radarChart"


/* Team Attributes */
BUILD_UP_PLAY_SPEED
BUILD_UP_PLAY_DRIBBLING
BUILD_UP_PLAY_PASSING
BUILD_UP_PLAY_POSITIONING
CHANCE_CREATION_PASSING
CHANCE_CREATION_CROSSING
CHANCE_CREATION_SHOOTING
DEFENCE_PRESSURE
DEFENCE_AGGRESSION
DEFENCE_TEAM_WIDTH


/* Player Attributes */
OVERALL_RATING
CROSSING
FINISHING
HEADING_ACCURACY
SHORT_PASSING
VOLLEYS
DRIBBLING
CURVE
FREE_KICK_ACCURACY
LONG_PASSING
BALL_CONTROL
ACCELERATION
SPRINT_SPEED
AGILITY
REACTIONS
SHOT_POWER
JUMPING
STAMINA
STRENGTH
LONG_SHOTS
AGGRESSION
INTERCEPTIONS
POSITIONING
VISION
PENALTIES
MARKING
STANDING_TACKLE
SLIDING_TACKLE
GK_DIVING
GK_HANDLING
GK_POSITIONING
GK_REFLEXES