/* Div IDs in Index.html */
COLLAPSIBLE_TREE_ID = "#collapsible_tree"
BAR_GRAPH_ID = "#bar_graph"
RADAR_CHART_ID = "#radarChart"
PARALLEL_COORDINATE_ID = "#parallel_coordinate"


/* Team Attributes */
BUILD_UP_PLAY_SPEED = 0
BUILD_UP_PLAY_DRIBBLING = 0
BUILD_UP_PLAY_PASSING = 0
BUILD_UP_PLAY_POSITIONING = 0
CHANCE_CREATION_PASSING = 0
CHANCE_CREATION_CROSSING = 0
CHANCE_CREATION_SHOOTING = 0
DEFENCE_PRESSURE = 0
DEFENCE_AGGRESSION = 0
DEFENCE_TEAM_WIDTH = 0


/* Player Attributes */
OVERALL_RATING = 0
CROSSING = 0
FINISHING = 0
HEADING_ACCURACY = 0
SHORT_PASSING = 0
VOLLEYS = 0
DRIBBLING = 0
CURVE = 0
FREE_KICK_ACCURACY = 0
LONG_PASSING = 0
BALL_CONTROL = 0
ACCELERATION = 0
SPRINT_SPEED = 0
AGILITY = 0
REACTIONS = 0
SHOT_POWER = 0
JUMPING = 0
STAMINA = 0
STRENGTH = 0
LONG_SHOTS = 0
AGGRESSION = 0
INTERCEPTIONS = 0
POSITIONING = 0
VISION = 0
PENALTIES = 0
MARKING = 0
STANDING_TACKLE = 0
SLIDING_TACKLE = 0
GK_DIVING = 0
GK_HANDLING = 0
GK_POSITIONING = 0
GK_REFLEXES = 0